services:
  - type: web
    name: compiler-service
    env: image
    plan: starter
    image:
      repo: docker.io/darkmortal69/onlineide:infinity
    # For image envs, Render reads the port exposed by the Dockerfile, 
    # but if you need to override or explicitly state it, it belongs under 'image'
