services:
  - type: web # Can be web, worker, private, or cron
    name: online-ide-service
    runtime: image # Required for prebuilt images
    image:
      url: docker.io/darkmortal69/onlineide:infinity
    plan: free # e.g., free, starter, standard
    region: ohio # Service region
